name: Release Workflow
on:
  push:
    tags:
      - v*.*.*

env:
  config: RelWithDebInfo

jobs:
  release:
    name: Release ${{ github.ref_name }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create environment variables
        run: |
          $prefix = "refs/tags/v"
          $version = $env:GITHUB_REF.Substring($prefix.Length)
          echo "RED4EXT_VERSION=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -DRED4EXT_IS_CI_RELEASE=YES `
            ${{ github.workspace }}

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${{ env.config }}

      - name: Prepare ZIP
        working-directory: build
        run: |
          $packagingDir = "./_packaging"

          # Create the necessary directories.
          New-Item -ItemType directory -Path $packagingDir
          New-Item -ItemType directory -Path $packagingDir/bin/x64
          New-Item -ItemType directory -Path $packagingDir/red4ext
          New-Item -ItemType directory -Path $packagingDir/red4ext/plugins

          # Copy the build artifacts.
          Copy-Item -Path ./${{ env.config }}/bin/d3d11.dll -Destination $packagingDir/bin/x64
          Copy-Item -Path ./${{ env.config }}/bin/RED4ext.dll -Destination $packagingDir/red4ext

          # Copy the license and third-party licenses.
          Copy-Item -Path ../LICENSE.md -Destination $packagingDir/red4ext/LICENSE.txt
          Copy-Item -Path ../THIRD_PARTY_LICENSES.md -Destination $packagingDir/red4ext/THIRD_PARTY_LICENSES.txt

          # Create the ZIP file.
          7z a red4ext_${env:RED4EXT_VERSION}.zip $packagingDir/*

      - name: Prepare ZIP (PDBs)
        working-directory: build
        run: |
          $packagingDir = "./_packaging_pdbs"

          # Create the necessary directories.
          New-Item -ItemType directory -Path $packagingDir
          New-Item -ItemType directory -Path $packagingDir/bin/x64
          New-Item -ItemType directory -Path $packagingDir/red4ext

          # Copy the PDBs.
          Copy-Item -Path ./${{ env.config }}/bin/d3d11.pdb -Destination $packagingDir/bin/x64
          Copy-Item -Path ./${{ env.config }}/bin/RED4ext.pdb -Destination $packagingDir/red4ext

          # Create the ZIP file.
          7z a red4ext_${env:RED4EXT_VERSION}_pdbs.zip $packagingDir/*

      - name: Generate hashes
        working-directory: build
        run: |
          # Generate the hash for the main ZIP and print it.
          $hash = Get-FileHash -Algorithm SHA256 -Path red4ext_${env:RED4EXT_VERSION}.zip
          $hash | Format-List

          $only_hash = $hash | ForEach-Object { $_.Hash }
          echo "RED4EXT_SHA256=${only_hash}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

          Write-Output "`n"

          # Generate the hash for the PDBs ZIP and print it.
          $hash = Get-FileHash -Algorithm SHA256 -Path red4ext_${env:RED4EXT_VERSION}_pdbs.zip
          $hash | Format-List

          $only_hash = $hash | ForEach-Object { $_.Hash }
          echo "RED4EXT_SHA256_PDBS=${only_hash}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

      - name: Upload assets
        uses: softprops/action-gh-release@fe9a9bd3295828558c7a3c004f23f3bf77d155b2 # Use commit hash instead of version,
                                                                                   # this commit introduce append_body
                                                                                   # option, which is not present in
                                                                                   # the release version.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          append_body: true
          body: |

            ### SHA256 Hashes of the release artifacts

            - red4ext_${{ env.RED4EXT_VERSION }}.zip
              - ${{ env.RED4EXT_SHA256 }}
            - red4ext_${{ env.RED4EXT_VERSION }}_pdbs.zip
              - ${{ env.RED4EXT_SHA256_PDBS }}
          files: |
            build/red4ext_${{ env.RED4EXT_VERSION }}.zip
            build/red4ext_${{ env.RED4EXT_VERSION }}_pdbs.zip
